### ISSUE TITLE
感觉不错，支持一下

### ISSUE THREAD

**Issue by missword2012** [hugeterry/coderfun#1]
download下来发现cn.hugeterry.coderfun.CoderfunKey丢失了，不过还是感谢分享。不知道啥情况- -，但是去你git目录下却能找到= =，默默下载，小白请原谅。。

**Comment by hugeterry** [comment]
sorry... CoderfunKey之前忘了commit进来了，早上才push的，所以下载的文件还没更新，显示就有了，过一会下载应该就没问题啦😋
