### ISSUE TITLE
图片名格式问题

### ISSUE THREAD

**Issue by cocoas** [hugeterry/coderfun#2]
一个小问题：
在AS中打开后，在mipmap文件夹中，有一张名为IOS_icon的图片，图片名格式报错。
另外，正好在学材料设计，感谢你的开源，谢谢。

**Comment by hugeterry** [comment]
谢谢你的反馈
图片命名要小写，这个之前我重命名过了，但是发现git好像对文件名字母大小写的同步分辨不太正常，所以出现了错误，git没有更新，把命名改一下就好了😋

**Comment by cocoas** [comment]
在看代码了，thanks~
