### ISSUE TITLE
WebView承载视频，Activity销毁后，视频资源没有被销毁

### ISSUE THREAD

**Issue by cocoas** [hugeterry/coderfun#3]
手机型号分别是:红米2A,Android4.4.4API19
                          红米Note3,Android5.0.2,API21

可以尝试在onDestroy之前修改url地址为空
或者调用webView的destroy方法

**Comment by hugeterry** [comment]
噢之前没想到这情况，忘记添加这个
刚刚添加上去修改了
谢谢你😋

**Comment by cocoas** [comment]
这算什么，你都开源了代码了 。多好啊
