### ISSUE TITLE
iOS_icon.png 命名不符合规范, 应该是a-z0-9_

### ISSUE THREAD

**Issue by oncealong** [hugeterry/coderfun#4]
```
Error: 'O' is not a valid file-based resource name character: File-based resource names must contain only lowercase a-z, 0-9, or underscore
```

这个问题只有我遇到么? 怎么都没说的. 把名字改为ios_icon.png就好. 
不过忽然发觉Android好黑, 竟然没法给一个资源起名叫iOS_icon.
![](http://oaa8t25yd.bkt.clouddn.com/coderfun/QQ%E6%88%AA%E5%9B%BE20160811210822.png)

**Comment by hugeterry** [comment]
这个跟文件名大小写都是后来重命名的，但是一直push上来，发现git一直没检测到，没有更新
谢谢你啦😙
