### ISSUE TITLE
'类CoderfunDb是公共的, 应在名为CoderfunDb.java的文件中声明'

### ISSUE THREAD

**Issue by oncealong** [hugeterry/coderfun#5]
```
错误: 类CoderfunDb是公共的, 应在名为CoderfunDb.java的文件中声明
```

这个问题也就我自己遇到么? 修改下类`CoderfunDb`所在的文件名为`CoderfunDb.java`就好了.
![](http://oaa8t25yd.bkt.clouddn.com/coderfun/QQ%E6%88%AA%E5%9B%BE20160811210955.png)

**Comment by hugeterry** [comment]
这个跟图片名都是后来重命名的，但是一直push上来，发现git一直没检测到，没有更新
谢谢你啦😙
