### ISSUE TITLE
资源文件里面有个大写

### ISSUE THREAD

**Issue by ZENGYANYAN** [hugeterry/coderfun#7]
孩子，图片文件里面有个大写iOS.png

**Comment by hugeterry** [comment]
图片命名要小写，这个之前我重命名过了，但是git对文件名字母大小写的同步分辨不太正常，所以出现了错误，git没有更新，把命名改一下就好了
😘

**Comment by tianshaokai** [comment]
文件删除后提交 然后重新添加就行了
